# Example training data
X_train = [
    #! XSS
    "An XSS vulnerability was found to affect the front page of the web.",
    "Cross-Site Scripting (XSS) vulnerability in MyBlogApp allows remote attackers to inject malicious scripts via crafted user-generated content.",
    "The XYZ Forum application before 2.5.3 allows stored XSS via a crafted user profile, leading to potential execution of arbitrary scripts.",
    "Cross-Site Scripting (XSS) in CoolShopApp 1.0.2 allows attackers to inject malicious code into product reviews, impacting user sessions.",
    "An issue in SocialNetworkApp 3.7.1 allows remote attackers to conduct reflected XSS attacks via specially crafted URLs.",
    "MyWalletApp 2.2.5 is vulnerable to persistent XSS attacks due to inadequate input sanitization in transaction descriptions.",
    "Crafted JavaScript payloads in ChatApp 4.0.0 lead to stored XSS, enabling attackers to compromise user accounts.",
    "Reflected XSS in FinanceTracker 1.5.7 allows attackers to trick users into executing malicious scripts via specially crafted links.",
    "Attackers exploit a DOM-based XSS vulnerability in MediaPlayerApp 5.3.2 by injecting scripts through manipulated URLs.",
    "The comment section of NewsPortal 2.1.0 is susceptible to stored XSS attacks, potentially impacting users who view the compromised content.",
    "A Cross-Site Scripting (XSS) flaw in ShoppingCartApp 3.0.1 enables attackers to inject malicious scripts into the checkout process, risking user data exposure.",
    "User profiles in SocialApp 1.5.0 are susceptible to reflected XSS attacks via specially crafted profile URLs.",
    "Crafted review content in ProductReviewApp 3.2.1 allows attackers to execute scripts when viewed by other users, leading to potential account compromise.",
    "A DOM-based XSS vulnerability in CommentSystem 2.0.7 enables attackers to manipulate comments to execute malicious scripts within victim's browsers.",
    "Malicious input in SearchEngineApp 4.1.2 leads to stored XSS, potentially compromising user search sessions.",
    "The XYZ Portal application 2.3.5 allows attackers to inject malicious scripts into news articles, impacting users who read the compromised content.",
    "Reflected XSS in FeedbackFormApp 1.0.0 permits attackers to execute scripts in the context of users who access specially crafted URLs.",
    "A stored XSS flaw in ProfileDashboard 2.1.1 allows attackers to inject scripts into user account settings, potentially leading to unauthorized actions.",
    "User-generated polls in VotingPlatform 3.5.2 are vulnerable to injected scripts, enabling attackers to manipulate poll results or steal user information.",
    "The messaging feature of ChatRoomApp 2.2.0 is susceptible to reflected XSS attacks when users click on specially crafted links.",
    "Vulnerable version of BloggingApp 1.1.0 permits attackers to inject scripts through crafted blog post titles, potentially impacting readers' browsers.",
    "An input validation flaw in UserCommentsApp 2.0.3 allows attackers to inject malicious scripts into comments, affecting users who view the compromised comments.",
    "Crafted event descriptions in CalendarApp 4.2.1 permit attackers to execute scripts, potentially disrupting user experience or stealing sensitive information.",
    "Reflected XSS vulnerability in OnlineStore 2.5.0 enables attackers to inject scripts via manipulated search queries, impacting users who perform those searches.",
    "The login page of AuthenticationSystem 1.0.5 is vulnerable to stored XSS, allowing attackers to execute scripts in the context of other users.",
    "Vulnerable version of RecipeBookApp 3.0.2 allows attackers to inject scripts through recipe names, potentially affecting users who browse the recipes.",
    "A DOM-based XSS flaw in InteractiveWidget 2.3.1 enables attackers to execute scripts via manipulated widget parameters, impacting visitors who view the widget.",
    "Attacker-crafted profile details in SocialNetworkApp 2.1.2 lead to stored XSS, potentially compromising user accounts or spreading malicious links.",
    "Reflected XSS in URLShortener 1.2.0 allows attackers to inject scripts via specially crafted short URLs, potentially redirecting users to malicious sites.",
    "The discussion board of ForumPlatform 3.2.3 is vulnerable to stored XSS, enabling attackers to inject scripts into forum posts and impact other users.",
    "Vulnerable version of PhotoSharingApp 2.0.4 allows attackers to inject scripts via captions of shared photos, potentially affecting user sessions and privacy.",
    #! Prvi esc
    "A vulnerability in AccessControlApp 1.2.0 allows unauthorized users to exploit privilege escalation and gain administrative rights.",
    "The role assignment feature in UserPermissions 3.1.1 is vulnerable to privilege escalation, enabling users to assign themselves higher privileges.",
    "Weak session validation in SessionManager 2.0.5 permits attackers to hijack sessions and achieve privilege escalation by impersonating other users.",
    "An issue in ProfileSettings 4.0.2 allows low-privileged users to manipulate their profiles and escalate privileges beyond their intended access.",
    "Insecure API endpoints in ServiceGateway 1.1.0 enable attackers to bypass authorization and achieve privilege escalation through specially crafted requests.",
    "Privilege escalation vulnerability in AdminDashboard 2.2.2 allows authenticated attackers to modify their user roles and gain unauthorized access.",
    "The authorization mechanism of SecureApp 3.5.1 is susceptible to bypass, enabling attackers to perform actions with escalated privileges.",
    "A flaw in AccountManagement 2.3.3 permits users with limited access to modify their account settings and achieve privilege escalation.",
    "Vulnerable version of AccessAPI 1.0.4 allows remote attackers to exploit privilege escalation by making unauthorized API calls.",
    "Weak input validation in RoleEditor 2.1.0 permits authenticated attackers to modify their role attributes and achieve privilege escalation.",
    "Insecure role validation in AccessControl 1.2.0 allows authenticated users to escalate privileges by modifying their assigned roles.",
    "A flaw in UserManagement 2.5.2 enables attackers to manipulate user permissions via specially crafted requests and gain elevated privileges.",
    "Weak authorization checks in DataAPI 3.0.1 permit remote attackers to escalate their privileges by making unauthorized API requests.",
    "The forgot password functionality in AccountService 4.2.0 is vulnerable to privilege escalation attacks, allowing users to reset other users' passwords.",
    "Inadequate session management in PortalApp 1.0.3 enables attackers to hijack active sessions and achieve unauthorized privilege escalation.",
    "The poorly secured API endpoint of ReportingTool 2.1.1 allows attackers to bypass authorization and achieve privilege escalation through API exploitation.",
    "A flaw in EmployeePortal 3.3.2 permits low-privileged employees to access sensitive data by exploiting a privilege escalation vulnerability.",
    "Weak access controls in ConfigurationManager 2.0.4 enable authenticated users to modify configuration settings and gain unauthorized elevated access.",
    "Privilege escalation is possible in ServiceControl 1.5.0 due to insufficient authorization checks, allowing attackers to perform administrative actions.",
    "The user registration process in OnlineStore 2.2.3 is vulnerable to privilege escalation, allowing attackers to create accounts with higher privileges.",
    # ? DoS
    "A vulnerability in NetworkService 1.1.0 allows remote attackers to trigger a denial of service by sending specially crafted network requests.",
    "Insufficient rate limiting in APIGateway 2.5.2 permits attackers to flood the system with requests, causing a denial of service for legitimate users.",
    "The authentication bypass vulnerability in AuthenticationModule 3.0.1 enables attackers to exhaust system resources and launch a denial of service attack.",
    "A flaw in DatabaseServer 4.2.0 allows attackers to send malicious database queries, leading to resource exhaustion and a denial of service.",
    "Insecure input validation in RequestHandler 5.1.0 enables attackers to craft malicious input, causing the service to become unresponsive and leading to a denial of service.",
    "The XML parsing functionality in DataParser 1.2.1 is vulnerable to specially crafted input, causing resource exhaustion and triggering a denial of service.",
    "Vulnerable version of LoadBalancer 2.0.3 allows attackers to flood backend servers with traffic, causing them to become overwhelmed and resulting in a denial of service.",
    "Weak session management in SessionManager 3.3.2 enables attackers to exhaust server resources by opening numerous concurrent sessions and initiating a denial of service.",
    "The SSL renegotiation vulnerability in WebServer 4.4.1 allows attackers to consume server resources and initiate a denial of service by repeatedly renegotiating SSL connections.",
    "A flaw in MessageQueue 5.0.4 allows attackers to flood the queue with malicious messages, causing resource exhaustion and leading to a denial of service.",
    # ? SQLi
    "An SQL injection vulnerability in LoginSystem 1.1.0 allows attackers to manipulate login queries and gain unauthorized access to accounts.",
    "Inadequate input validation in SearchFunctionality 2.5.2 permits attackers to execute arbitrary SQL queries, potentially compromising the database.",
    "The user input validation in RegistrationForm 3.0.1 is weak, allowing attackers to inject malicious SQL statements and potentially manipulate the database.",
    "A flaw in ProductCatalog 4.2.0 permits attackers to manipulate SQL queries through crafted product IDs, potentially disclosing sensitive information.",
    "Insufficient input sanitization in CommentSection 5.1.0 enables attackers to inject malicious SQL code, potentially compromising user data.",
    "Vulnerable version of ReportGenerator 1.2.1 allows attackers to manipulate SQL queries via specially crafted parameters, potentially accessing unauthorized data.",
    "The product search functionality in ECommerceApp 2.3.2 is vulnerable to SQL injection, allowing attackers to extract sensitive data from the database.",
    "An issue in UserProfiles 3.4.0 permits attackers to inject malicious SQL statements through profile inputs, potentially exposing user data.",
    "Weak input validation in SearchBar 4.5.0 allows attackers to insert malicious SQL code, potentially retrieving unauthorized information.",
    "The comment submission form in BlogPlatform 5.0.3 is susceptible to SQL injection, enabling attackers to manipulate the underlying database.",
]


cia_output = [
    # ? XSS
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    {"confidentiality": "low", "integrity": "low", "availability": "none"},
    # ? Priv esc
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    {"confidentiality": "high", "integrity": "high", "availability": "high"},
    # ? Denial of Service
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    {"confidentiality": "none", "integrity": "none", "availability": "high"},
    # ? SQLi
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
    {"confidentiality": "high", "integrity": "low", "availability": "none"},
]
